project:
  type: website
  output-dir: docs

website:
  navbar:
    search: true

title: 'Update Facharztmangel im ÖGD'
subtitle: "Haben die Entwicklungen rund um die Coronapandemie die Anzahl an Fachärzten für öffentliches Gesundheitswesen erhöht?"
lang: de
date: "2025-06-16"
keywords: Facharzt
author:
  - name: Jakob Schumacher
    affiliations: Robert Koch-Institut
    affiliation-url: https://rki.de
    email: schumacherj@rki.de
    orcid: 0000-0002-9894-6085
  - name: Peter Tinnemann
    affiliations: Gesundheitsamt Frankfurt
    affiliation-url: https://frankfurt.de/service-und-rathaus/verwaltung/aemter-und-institutionen/gesundheitsamt

execute:
  echo: false

format:
  html:
    toc: true
